global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'opentelemetry-collector'
    static_configs:
      - targets: ['172.17.84.53:8888']
  - job_name: 'demo-app'
    static_configs:
      - targets: ['172.17.84.53:8889']
  - job_name: 'java-demoapp-actuator'
    static_configs:
      - targets: ['172.17.84.53:8080']
    metrics_path: '/actuator/prometheus'
