version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Adjust heap size as needed
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
    ports:
      - "9200:9200"
      # - "9300:9300" 
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Linking Kibana to Elasticsearch
    ports:
      - "5601:5601"  # Kibana port



  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.95.0
    container_name: otel-collector
    ports:
      - "4317-4318:4317-4318/tcp"
      - "55679:55679"
      - "8888:8888"
      - "8889:8889"
    environment:
      OTLP_EXPORTER_ENDPOINT: "http://172.17.84.53:14268/api/traces"
    volumes:
      - ./confs/otel-collector.yml:/etc/otel-collector.yml
    command: --config=/etc/otel-collector.yml
    restart: unless-stopped

  java-demoapp:
    image: java-demoapp
    ports:
      - "8080:8080"
      # - "9100:9100"
  zipkingui:
    image: openzipkin/zipkin:latest
    container_name: zipkingui
    ports:
      - "9411:9411"

  prometheus:
    image: quay.io/prometheus/prometheus:v2.49.1
    ports:
      - "9090:9090"
    volumes:
      - ./confs/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml


  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./confs/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"

volumes:
  esdata:
    driver: local
